### ISSUE TITLE
คิดชื่อเกมที่จะทำ

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#1]
การสร้างเกมสักเกมควรจะมีชื่อเกมที่เหมาะสม

**Comment by Hewkai** [comment]
เพื่อนอยากสร้างเกมไรกันอ่ะ

**Comment by Rehunt671** [comment]
เกมแนวตายเกิดรัวๆดูน่าสนถือว่าฝึกความอดทน

**Comment by Rehunt671** [comment]
สรุปชื่อเกมคือ bullet hell ที่ได้จากการโหวตเป็นส่วนมาก
