### ISSUE TITLE
ออกแบบ และ  Import Character ไม้ที ในวิชาดรออิ้ง

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#19]

**Comment by Hewkai** [comment]
![โดดซ้าย](https://user-images.githubusercontent.com/110963185/189125483-d7688107-1ce8-4d62-a0d3-43b86a0706d0.png)
![ไม้ที ขวา](https://user-images.githubusercontent.com/110963185/189125500-5aca8733-e2b4-4d54-9016-8a9096b70a28.png)
![ไม้ที](https://user-images.githubusercontent.com/110963185/189125506-e37c47b0-d74a-49eb-9e4e-4eb544a94141.png)
![โดดขวา](https://user-images.githubusercontent.com/110963185/189125510-960a2181-5c6b-4776-b9c2-5473ac55541e.png)

**Comment by Hewkai** [comment]
เดินหันซ้าย
![เดินซ้าย](https://user-images.githubusercontent.com/110963185/189141038-91080245-6207-4339-8d0e-111e268e8675.gif)
เดินหันขวา
![ขวา](https://user-images.githubusercontent.com/110963185/189141115-eb660c4e-0e61-4050-b4f3-550736c20d55.gif)
