### ISSUE TITLE
คิดTheme game ที่จะทำ

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#2]
เกมทุกเกมย่อมมีแนวเกมของตัวเอง ไม่ว่าจะเป็น Moba Rpg Fps Soulgame Racing Sports Action Survival Sim
Strategy ดังนั้นจะสร้างเกมสักเกมต้องมีแนวเกมที่จะสร้างก่อน

**Comment by Hewkai** [comment]
![งานหยาบ](https://user-images.githubusercontent.com/110963185/185083759-ec76f198-c0b4-427c-b9b3-4455231c25de.png)
อันนี้คิดไว้คร่าวๆ

**Comment by Nina-pw** [comment]
![87F32F51-F5B5-4387-B677-3956E1109A7A](https://user-images.githubusercontent.com/110963696/185203796-331780a3-d81b-4526-883e-8ebb57324956.jpeg)
อันนี้ของเราที่คิดไว้นะ (สามารถปรับเปลี่ยนได้ตามเหมาะสมเลยฮะ)

**Comment by Nina-pw** [comment]
อาทิตย์สอบก็ผ่านไปแล้ว เป็นยังไงกันบ้างทุกคนนน ขอให้ผลเป็นไปตามที่ทุกคนหวังไว้นะ ส่วนพวกเรามาลุยงานกันต่อเถอะ Fight!!!!

**Comment by Rehunt671** [comment]
![images jpeg](https://user-images.githubusercontent.com/105868841/188431093-d756da54-1f1b-47c3-ad6a-317d08693340.jpg)
ต้นแบบเกมชื่อมาจากเกมชื่อ Brian's Adventure เกมที่จะนำพาความชิบหายสู่ คีบอร์ดและอารมณ์ของผู้เล่น รายละเอียดคร่าวๆคือไบรอันจะออกเดินทางไปช่วยเจ้าหญิงที่ถูกปีศาจจับตัวไป แต่การเดินทางของเขาไม่ได้เต็มไปด้วยกลีบกุหลาบแต่เต็มไปด้วยความซวยเพราะไม่ว่าจะเดินไปทางไหน หรือทำอะไร ก็มีแต่ตายกับตาย(แต่ตายแบบไม่น่าตายเอาซะเลย) จุดประสงค์เกมนี้คือจะทำให้ผู้เล่นฝึกความอดทน และ ใช้สมองในการไตร่ตรองสิ่งที่จะทำหรือในการตอบคำถามกับNpc

**Comment by Maimeetang** [comment]
![0](https://user-images.githubusercontent.com/110970005/188437407-ee6fe4ba-cbc2-4189-a33e-888d8e4674af.jpg)
![image](https://user-images.githubusercontent.com/110970005/188437434-25753576-f446-44c9-b839-99d971098e3e.png)

**Comment by Rehunt671** [comment]
โหวต bullet hell +1

**Comment by Nina-pw** [comment]
โหวต bullet hell เหมือนกัน

**Comment by Rehunt671** [comment]
เป็นอันสรุปว่าเลือกเกมที่จะทำคือเกม bullet hell
