### ISSUE TITLE
ออกแบบ และ  Import Character ไม้45  ในวิชาดรออิ้ง

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#20]

**Comment by Hewkai** [comment]
![up](https://user-images.githubusercontent.com/110963185/189139388-93fd2b7f-b3e8-4ad3-893e-16def756657f.png)
![normal](https://user-images.githubusercontent.com/110963185/189139399-3680191c-cb0e-4adf-a1ba-9214c26c167c.png)
![right](https://user-images.githubusercontent.com/110963185/189139402-84a1e948-f60b-46a8-923f-8f26156263a0.png)

**Comment by Hewkai** [comment]
อนิเมชั่นตอนเดิน
![ezgif-1-cdad80e1a0](https://user-images.githubusercontent.com/110963185/189140076-d2d29f9d-c685-4174-91a6-f9ff8fbd53c1.gif)
