### ISSUE TITLE
ออกแบบ และ  Import Character ไม้ 30 ในวิชาดรออิ้ง

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#21]

**Comment by Hewkai** [comment]
![down](https://user-images.githubusercontent.com/110963185/189129473-aac58f59-ae9e-4aa0-8cc9-5c19773ec997.png)
![normal](https://user-images.githubusercontent.com/110963185/189129477-bf6ab372-f1af-4746-9187-be21d97e9138.png)
![up side down](https://user-images.githubusercontent.com/110963185/189129480-3052fed9-c0ed-4911-9ab7-8e2b29554f90.png)
![up](https://user-images.githubusercontent.com/110963185/189129484-05d40779-3e44-43dd-bb44-3e5c941df627.png)

**Comment by Hewkai** [comment]
อนิเมชั่นตอนเดิน
![ezgif-1-41349b97c8](https://user-images.githubusercontent.com/110963185/189134951-282dcfde-baed-4469-b6dd-a88e4f38afc9.gif)
