### ISSUE TITLE
ออกแบบ และ  Import Character หน้าX(ตีใกล้) ในวิชาแคล

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#22]

**Comment by Hewkai** [comment]
เดินซ้าย
![1](https://user-images.githubusercontent.com/110963185/189880467-00ecbb9d-4559-485d-a359-f10eedbf0752.gif)
![เดิน](https://user-images.githubusercontent.com/110963185/189880492-d7b25c1b-bd07-4f82-833b-4895a734d25f.png)
![ยืน](https://user-images.githubusercontent.com/110963185/189880503-97e3a2f8-378b-4a60-a1f3-600ae83ee94f.png)

**Comment by Hewkai** [comment]
เดินขวา
![2](https://user-images.githubusercontent.com/110963185/189880589-064bada8-c443-4704-8c07-5483b4089b75.gif)
![เดิน ขวา](https://user-images.githubusercontent.com/110963185/189880640-e2601fbf-e463-46e1-a3db-d7424fc1d594.png)
![ยืน ขวา](https://user-images.githubusercontent.com/110963185/189880648-0a6b3707-7265-40bd-82bc-a8a189a12497.png)
