### ISSUE TITLE
ออกแบบ และ  Import Character ธนู ในวิชาแคล

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#23]

**Comment by Hewkai** [comment]
หันซ้าย
![ซ้าย](https://user-images.githubusercontent.com/110963185/189888345-3086942c-e6bc-4a62-ab1c-fc2249013588.gif)
![เดิน](https://user-images.githubusercontent.com/110963185/189888363-dc1f87b6-e626-483c-8a75-f8b3c51e7d88.png)
![ยืน](https://user-images.githubusercontent.com/110963185/189888366-9089a64f-058c-459c-9b7a-b03583a8632d.png)
![กระสุน](https://user-images.githubusercontent.com/110963185/189888367-ac8cad1b-b3f2-42f4-bff5-e4de8f198bcf.png)
หัวขวา
![ขวา](https://user-images.githubusercontent.com/110963185/189888409-7b9d38da-64c4-4a20-a03b-741290998230.gif)
![ยืน ขวา](https://user-images.githubusercontent.com/110963185/189888430-94233c7d-960e-4c79-b600-8ee62b3bc0ea.png)
![กระสุน ขวา](https://user-images.githubusercontent.com/110963185/189888436-f9c755af-adae-42ef-9399-e84c444e53b0.png)
![เดิน ขวา](https://user-images.githubusercontent.com/110963185/189888438-5e386e52-3bc6-4c17-ac64-2cb5dd6d8418.png)
ตัวอย่างตอนยิง
![ตอนยิง](https://user-images.githubusercontent.com/110963185/189888463-a3d5a0b0-3bef-4247-b0cb-5b6ba8ab48d6.gif)
