### ISSUE TITLE
ออกแบบ และ  Import Character โล่ ในวิชาฟิสิกส์

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#24]

**Comment by Hewkai** [comment]
เดินซ้าย
![ช้าย](https://user-images.githubusercontent.com/110963185/189895149-4082420f-f1ed-4ac3-b926-1c265a3ddbb8.gif)
![เดิน](https://user-images.githubusercontent.com/110963185/189895168-200d9cef-73bf-4344-9015-473e0530725b.png)
![ยืน](https://user-images.githubusercontent.com/110963185/189895169-e1710444-70af-40e3-bcaa-c0a9c9f19ca6.png)
เดินขวา
![ขวา](https://user-images.githubusercontent.com/110963185/189895222-2a985763-a43f-4354-8aae-7652506a3614.gif)
![เดิน ขวา](https://user-images.githubusercontent.com/110963185/189895282-4d339cb0-825b-49ac-b2e7-bb7f3b2aaf2c.png)
![ยืน ขวา](https://user-images.githubusercontent.com/110963185/189895286-393cfd85-463a-406b-88b5-e4948f8bfa40.png)
