### ISSUE TITLE
ออกแบบ และ  Import Character บอสวงเวียน ในวิชาดรออิ้ง

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#25]

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/189365195-fd2bb33c-f52e-4305-86f6-d3553f5e36de.MOV

**Comment by Nina-pw** [comment]
อันนี้คือลองใช้ตัวละครอื่นในการเขียน Code ก่อนนะ เลยอยากให้ออกแบบขาของวงเวียนให้ยาวหน่อยนะ ตอนมันหมุนจะได้ดู smooth กว่านี้จะได้ตีวงได้โอเคขึ้น

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/189365881-59a2404d-f662-4a03-bff0-4d14ef674feb.mp4

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/189366299-9a16a1b1-821e-4bbf-ba10-2f932a2c8904.mp4

**Comment by Hewkai** [comment]
เดินซ้าย
![ซ้าย](https://user-images.githubusercontent.com/110963185/189953690-42b2a598-d8c4-4d01-a063-8b6e4bc17922.gif)
![เดิน](https://user-images.githubusercontent.com/110963185/189953725-339baa60-5dea-40e0-9150-9c7caa55a873.png)
![ยืน](https://user-images.githubusercontent.com/110963185/189953731-fcc9d124-1191-4157-86e2-1009b1e427f9.png)
เดินขวา
![ขวา](https://user-images.githubusercontent.com/110963185/189954132-93c6cf77-1fb2-4dfa-aaf0-b55574f4b220.gif)
![เดิน ขวา](https://user-images.githubusercontent.com/110963185/189954146-f788cec1-565e-46ee-a32f-56048108c79d.png)
![ยืน ขวา](https://user-images.githubusercontent.com/110963185/189954148-da52f28e-0e68-4658-8659-ac600f635fe5.png)

**Comment by Hewkai** [comment]
ท่าไม้ตาย
หันขวา
![1 ขวเ](https://user-images.githubusercontent.com/110963185/189954640-5cfd0084-8029-49a0-9792-b2616ed21894.png)
หันซ้าย
![1](https://user-images.githubusercontent.com/110963185/189954709-92e5eee8-bd0e-4df1-ba1c-d254ab7c1ce5.png)
ตอนหมุน
![2](https://user-images.githubusercontent.com/110963185/189954754-33371ec7-ec99-4eba-8fcb-237e20335b06.png)
![3](https://user-images.githubusercontent.com/110963185/189954764-0a24a052-0ce3-4727-895e-93f061ecdd21.png)
ตัวอย่างอนิเมชั่น
![ezgif-1-69aa68bd8f](https://user-images.githubusercontent.com/110963185/189954879-38517e5e-4a43-4221-8ca4-2499f8d10e3b.gif)
