### ISSUE TITLE
ออกแบบ และ  Import Character บอสไททั่น ในวิชาแคลคูลัส

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#26]

**Comment by Hewkai** [comment]
ตัวอย่างการเดิน
![เดิน](https://user-images.githubusercontent.com/110963185/190888638-f6820790-b97a-4edc-bbc6-4f9b74f85d01.gif)

เดินซ้าย
![เดิน1](https://user-images.githubusercontent.com/110963185/190888692-5e80d570-d45e-45c4-b58f-5410dbb7b452.png)
![เดิน2](https://user-images.githubusercontent.com/110963185/190888652-1fa7d23e-ee5e-4c9e-9d37-e0a0056dee8d.png)
![ยืน](https://user-images.githubusercontent.com/110963185/190888654-bda1dbc7-0231-4c23-8980-981e792bb296.png)

เดินขวา
![เดิน1 ขวา](https://user-images.githubusercontent.com/110963185/190888667-6c78af97-895c-47ab-a8e6-0332905a455a.png)
![เดิน2 ขวา](https://user-images.githubusercontent.com/110963185/190888669-7cafda6c-7bec-438d-84d8-4159275f53f8.png)
![ยืน ขวา](https://user-images.githubusercontent.com/110963185/190888670-797588ac-1710-4546-b61d-b47488f02f52.png)

**Comment by Hewkai** [comment]
ตัวอย่างใช้ท่าไม้ตาย
![ทุบ](https://user-images.githubusercontent.com/110963185/190888716-b138e134-a907-4858-96ea-321206b06e2e.gif)

หันซ้าย
![ทุ่ม](https://user-images.githubusercontent.com/110963185/190888728-f6fc2cd7-859d-43d9-8f9d-f4a8065b5a31.png)
![ทุ่ม2](https://user-images.githubusercontent.com/110963185/190888730-4e4e9303-cf22-4b45-8901-3f9e2a7d6410.png)
![ทุ่ม3](https://user-images.githubusercontent.com/110963185/190888731-201162a4-cb06-417a-8caf-78ea258a1d30.png)
![ยืน2](https://user-images.githubusercontent.com/110963185/190888732-477d02d0-92f8-4efb-bea0-f92b5ecf8233.png)

หันขวา

![ทุ่ม ขวา](https://user-images.githubusercontent.com/110963185/190888738-0ea8f920-c792-42ba-ac9c-cccfec9b9ab4.png)
![ทุ่ม2 ขวา](https://user-images.githubusercontent.com/110963185/190888740-d44ddc87-da90-4f53-b59b-4c0a2e125df0.png)
![ทุ่ม3 ขวา](https://user-images.githubusercontent.com/110963185/190888741-606b2118-6ab8-485c-a201-d32ce5cb543c.png)
![ยืน2 ขวา](https://user-images.githubusercontent.com/110963185/190888742-1150ce90-b7f4-409a-aade-b418bd240b20.png)
