### ISSUE TITLE
ออกแบบ และ  Import Character บอสไอแซค ในวิชาฟิสิกส์

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#27]

**Comment by Hewkai** [comment]
การเดิน
![เดิน](https://user-images.githubusercontent.com/110963185/190895260-f4d7b07c-f2a0-4b99-8ad5-eed3fcaedf28.gif)

หันซ้าย
![1](https://user-images.githubusercontent.com/110963185/190895269-760a7344-0b05-4140-8e44-58611be0c16f.png)
![2](https://user-images.githubusercontent.com/110963185/190895270-f3d34286-50fc-42bd-a6d1-7d55077974a7.png)

หันขวา
![1 ขวา](https://user-images.githubusercontent.com/110963185/190895277-2cef04de-c2b6-4ff6-82f6-b3d651d322b2.png)
![2 ขวา](https://user-images.githubusercontent.com/110963185/190895278-dcb29f91-ef87-4d11-b526-873984760ad1.png)

**Comment by Hewkai** [comment]
ร่ายเวท
![ร่ายเวท](https://user-images.githubusercontent.com/110963185/190895295-038295df-50fb-4940-976c-f09c8b20ce02.gif)

หันซ้าย
![3](https://user-images.githubusercontent.com/110963185/190895328-231bf77b-541c-496e-a63e-feddd3ee6ed1.png)
![4](https://user-images.githubusercontent.com/110963185/190895324-ebd5aa1b-b188-4882-ac46-2bc6da7048c8.png)
![5](https://user-images.githubusercontent.com/110963185/190895325-4cb998d0-0d5b-42fb-818e-4b061812f146.png)
![6](https://user-images.githubusercontent.com/110963185/190895326-dc543252-1c3b-40b2-aa53-e279de1028e6.png)
![7](https://user-images.githubusercontent.com/110963185/190895327-af36c22e-9b93-485c-856e-4fa15ca211ed.png)

หันขวา

![3 ขวา](https://user-images.githubusercontent.com/110963185/190895359-66ce3438-1d17-4836-9ffd-4499dce1f342.png)
![4 ขวา](https://user-images.githubusercontent.com/110963185/190895361-fa0311c4-88da-488a-b687-bd7ed2448ded.png)
![5 ขวา](https://user-images.githubusercontent.com/110963185/190895362-e3e76653-2c6b-4c09-8e72-843e649e9c40.png)
![6 ขวา](https://user-images.githubusercontent.com/110963185/190895363-3d5d310b-0482-4f31-8dfa-54faff478252.png)
![7 ขวา](https://user-images.githubusercontent.com/110963185/190895364-76fd7660-8d2f-4e02-ac6a-fae1b605a8d5.png)

**Comment by Hewkai** [comment]
มอนที่เกิด
![appple](https://user-images.githubusercontent.com/110963185/190895717-38dfc82c-7693-41d9-98cb-4723ab5ee3ee.gif)

หันซ้าย
![a2](https://user-images.githubusercontent.com/110963185/190895724-456ab74f-79f5-4153-a247-1ff1108b37ce.png)
![a1](https://user-images.githubusercontent.com/110963185/190895726-f426cfb1-a217-4044-bfff-462fbb72a5ec.png)

ขวา
![a1 ขวา](https://user-images.githubusercontent.com/110963185/190895733-2c15e619-bb6a-44b5-b169-af463097ef2b.png)
![a2 ขวา](https://user-images.githubusercontent.com/110963185/190895734-03516d06-4422-4de6-b316-972f0d1863f1.png)
