### ISSUE TITLE
ออกแบบ และ  Import Character Scratch(Final Boss)

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#28]

**Comment by Hewkai** [comment]
![1 ขวา](https://user-images.githubusercontent.com/110963185/190895907-1ddb0039-86a0-462f-aac4-9bd3cee5c028.png)
![1](https://user-images.githubusercontent.com/110963185/190895908-d746903b-3d6d-4e72-8ae8-9dcb8f1c38b1.png)
