### ISSUE TITLE
ออกแบบ และ  Import Character ตัวละครหลัก

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#29]

**Comment by Hewkai** [comment]
![Normal Left](https://user-images.githubusercontent.com/110963185/189121218-d5767a6b-395b-4b45-8222-ea61c0784d02.png)
![Normal right](https://user-images.githubusercontent.com/110963185/189121223-dbeb1393-1ca7-4103-b5f2-eaf07b012d2a.png)
![walk left](https://user-images.githubusercontent.com/110963185/189121227-eb2c5c08-42de-4fdf-9b2e-c95f6d8e4a4a.png)
![walk right](https://user-images.githubusercontent.com/110963185/189121233-870c07ca-96ff-4b3f-9126-ffc6db352cdc.png)

**Comment by Hewkai** [comment]
![Normal right](https://user-images.githubusercontent.com/110963185/189121776-e6e7061b-3271-4827-b95f-db72c85ef114.png)
![walk right](https://user-images.githubusercontent.com/110963185/189121781-7985a140-c54e-45e7-b037-121621462a91.png)
