### ISSUE TITLE
คิดระบบเกมที่จะสร้าง รายละเอียดเกม เป้าหมายของเกม สิ่งที่น่าดึงดูดผู้เล่น 

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#3]
สิ่งเหล่านี้ย่อมเป็นสิ่งสำคัญในการสร้างเกมทั้งนั้น ดังนั้น เป็นสิ่งที่ต้องตระหนักและคำนึงถึงเสมอ และควรอยู่ในขอบเขตการสร้างที่เหมาะสมเนื่องจากทำเพียง 4 คน

**Comment by Rehunt671** [comment]
เป้าหมายเกม คือทำให้ผู้เล่นสนุกและท้าย และสิ่งนี้จะเป็นสิ่งที่ดึงดูดผู้เล่น

**Comment by Asura671** [comment]
ะ

**Comment by Rehunt671** [comment]
ส่วนคำถามอื่นในที่นี้ขอตอบไปในรูปใน theme issue
