### ISSUE TITLE
ออกแบบ ไอเทมหนังสือเรียน และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#30]

**Comment by Rehunt671** [comment]
โดยไอเทมนี้จะเป็นไอเทมในกลุ่มช่วยตีที่จะวนรอบเราและทำให้ศัตรูได้รับดาเมจ

**Comment by Hewkai** [comment]
Icon ปกติ(1-2)
![1](https://user-images.githubusercontent.com/110963185/190901112-3765d683-9ee6-41e5-8790-dfc8933ca1d9.png)
Max(Lv.3)
![max](https://user-images.githubusercontent.com/110963185/190901113-bf7016d0-813f-4d73-b658-ea917bc55160.png)

อาวุธในเกม
![ตัวจริง](https://user-images.githubusercontent.com/110963185/190901114-9c1d1753-4096-47ff-8354-4c3fe1736cce.png)
