### ISSUE TITLE
ออกแบบ ไอเทมคอร์สติวเตอร์ และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#31]

**Comment by Hewkai** [comment]
![NewCanvas13](https://user-images.githubusercontent.com/110963185/190901250-7d3399bf-5281-41d8-b955-c2289c45fb76.png)

เก็บแล้วจะขึ้นสถานะตีแรงกับวิ่งไว
