### ISSUE TITLE
ออกแบบ ไอเทมค่ายาใจ(แสดงผลในรูปแบบโล่?)  และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#33]

**Comment by Hewkai** [comment]
Icon ปกติ(Lv1-2)
![normal](https://user-images.githubusercontent.com/110963185/190901687-1c1cf791-48b2-40bc-81a5-83dd17aa5e40.png)
Max(Lv3)
![max](https://user-images.githubusercontent.com/110963185/190901689-715edca7-1830-4b34-92b8-083e6e05bce1.png)
in game
![โล่](https://user-images.githubusercontent.com/110963185/190901688-1c0b1dc9-66c3-4a12-8757-e762bc0e9f8b.png)

**Comment by Hewkai** [comment]
ตัวอย่าง
![ตัวอย่าง](https://user-images.githubusercontent.com/110963185/190901863-69014c09-3f83-483a-a19d-354370a3c0f9.png)
