### ISSUE TITLE
ออกแบบ Interface หน้าเกม และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#36]

**Comment by Asura671** [comment]
โดยมี 3 ฉากหลังตามวิชา

**Comment by Rehunt671** [comment]
หน้าเริ่มเกมแล้วแต่จะ Design ขอดึงดูดผู้เล่นจะดีมาก

**Comment by Hewkai** [comment]
![ตัวอย่างหลัก](https://user-images.githubusercontent.com/110963185/190900676-510f8ab5-56ad-4a9e-8998-d9f8c2de8c32.png)

**Comment by Hewkai** [comment]
ตัวอย่างหน้าเริ่มเกม
![wallpaper 2](https://user-images.githubusercontent.com/110963185/191018193-c66b4b1a-fcc0-4029-a348-781436efa6ce.png)
![wallpaper1](https://user-images.githubusercontent.com/110963185/191018202-0b45073e-7f51-4d90-a5ee-fb4fabb8c7cf.png)

ภาพ1
![wallpaper1](https://user-images.githubusercontent.com/110963185/191018294-a803267c-7308-44e0-9c0b-e8dd275d82a9.png)

ภาพ2
![wallpaper](https://user-images.githubusercontent.com/110963185/191018318-071e6152-31b7-4af0-8ce3-3422c2c7f429.png)

ปุ่ม
![cradit](https://user-images.githubusercontent.com/110963185/191018342-e7d971fc-2b02-4e9d-83f8-f198c7fd1271.png)
![start](https://user-images.githubusercontent.com/110963185/191018346-1e85d48d-5066-4847-b992-e629bc8853f1.png)

logo  อันที่ใช้อยู่ตอนนี้
![logo 1](https://user-images.githubusercontent.com/110963185/191018500-ebfdaa2a-aa1c-4ff1-86ce-c73d356eca64.png)
![logo 2](https://user-images.githubusercontent.com/110963185/191018503-dfe1fd18-3b55-404d-90d3-ac2f3fbb98ee.png)

ตัวหลัก
![main](https://user-images.githubusercontent.com/110963185/191018614-71a4a808-413f-4864-8d8f-87f64b32d2b7.png)
![enemy](https://user-images.githubusercontent.com/110963185/191018623-65a43dfa-f94b-49c3-8026-9419211a62af.png)

พื้นหลัง
![background](https://user-images.githubusercontent.com/110963185/191018667-437f1538-8bf2-426c-bbf8-2baae4ed05fc.png)

**Comment by Rehunt671** [comment]
เชี่ยสุดเกิน

**Comment by Hewkai** [comment]
แสบตาเลย :')
