### ISSUE TITLE
ออกแบบ Interface หน้าCredit และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#37]

**Comment by Rehunt671** [comment]
Credit ให้ เสียงเกม Hollow Knight หน่อยก็ดี

**Comment by Hewkai** [comment]
หน้าเครดิต
![1](https://user-images.githubusercontent.com/110963185/191040429-e1ddb65e-03a6-4bed-b0f1-db9fa53c4867.png)

พื้นหลัง
![bg](https://user-images.githubusercontent.com/110963185/191040479-d36f8db0-e6d1-4c84-9b27-973b953ca8b1.png)

น้อน
![น้อน](https://user-images.githubusercontent.com/110963185/191040533-1e7d1dbf-3ab5-4e3c-85fa-d87e2c35f2d5.png)

ตัวหนังสือ
![Text](https://user-images.githubusercontent.com/110963185/191040561-20a9a345-6b96-436b-b991-2e06013e3d57.png)
