### ISSUE TITLE
Slide นำเสนอหัวข้อโครงงาน

### ISSUE THREAD

**Issue by Nina-pw** [Asura671/Scratch-game-for-group-8#4]
คิดชื่อเกม แนวเกม และ Theme ของเกมได้แล้ว จากนั้นก็ทำ slide นำเสนอหัวข้อโดยแสดงให้เห็นว่าเกมหน้าตาเป็นอย่างไร เล่นยังไง และสมาชิกแต่ละคนทำหน้าที่อะไรบ้าง ออกแบบให้น่าสนใจโดยให้เกี่ยวข้องกับ Theme ที่กลุ่มเราเลือก

**Comment by Hewkai** [comment]
![หน้าต่างเริ่มเกม](https://user-images.githubusercontent.com/110963185/188661125-1a83ba55-4700-437d-8df6-7a48e0f3b552.png)
![หน้าต่างเริ่มเกม2](https://user-images.githubusercontent.com/110963185/188661147-cb4f3eb6-da47-4a5a-9ab9-5c5e23c094e4.png)
![Theme](https://user-images.githubusercontent.com/110963185/188661149-21dfce66-099d-473e-a0cf-f72c0a0aa89f.png)
![งานหยาบ2](https://user-images.githubusercontent.com/110963185/188661154-7021d93f-2ab7-4d91-bbbd-568dbfdf9052.png)

**Comment by Nina-pw** [comment]
https://www.canva.com/design/DAFLYVPjj04/dxXlYJS_t9Oz4PtC21rKYQ/edit?utm_content=DAFLYVPjj04&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/188671653-3e5d12ae-3496-4a8b-b3a1-5c3fb87cbe41.mp4

**Comment by Nina-pw** [comment]
สไลด์นำเสนอหัวข้อโครงงานคร่าวๆประมาณนี้
