### ISSUE TITLE
ออกแบบ Interface หน้าแจ้งเตือนก่อนถึงบอส และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#40]

**Comment by Rehunt671** [comment]
Wave 1-15 เลขเปลี่ยนเฉยๆ

**Comment by Hewkai** [comment]
เจอบอสวงเวียน
![1](https://user-images.githubusercontent.com/110963185/191264713-71939381-e92f-42d3-9c03-23baf46350fa.png)
![2](https://user-images.githubusercontent.com/110963185/191264726-bb34c2eb-00db-4deb-b1b4-db8df7201083.png)
![3](https://user-images.githubusercontent.com/110963185/191264734-1583b815-e2b0-41b4-8154-68ef89b491f9.png)
![4](https://user-images.githubusercontent.com/110963185/191264740-733cc59c-448c-431e-94f0-2f534cdc39e4.png)
![5](https://user-images.githubusercontent.com/110963185/191264745-ad7604aa-43b8-49ec-9844-a39cfd624942.png)

ไปแมพแคล
![6](https://user-images.githubusercontent.com/110963185/191264829-9a92141b-4a40-4677-be63-74ae57832667.png)
![7](https://user-images.githubusercontent.com/110963185/191264840-70f242c0-3edb-4bec-ae58-b563d03c9fa7.png)
![8](https://user-images.githubusercontent.com/110963185/191264844-2a6abc97-0dcd-4aaf-b9aa-b44efef96a4d.png)
![9](https://user-images.githubusercontent.com/110963185/191264847-47020b29-6f30-4b9d-b82f-e1d5c57da31a.png)

เจอบอสแคล
![1](https://user-images.githubusercontent.com/110963185/191264957-a0096955-9d44-4eb0-98dc-14af1eab30c9.png)
![2](https://user-images.githubusercontent.com/110963185/191264965-e777d8c9-f306-4ac0-8152-087f30837b60.png)

ไปแมพฟิสิกส์
![3](https://user-images.githubusercontent.com/110963185/191264969-b49ae222-6eca-41c1-a8b4-712b24c910a3.png)
![4](https://user-images.githubusercontent.com/110963185/191264971-46310573-b957-4bd1-ac4e-8f210540b13a.png)
![5](https://user-images.githubusercontent.com/110963185/191264975-301c66e1-b949-407d-a0a2-00509343190c.png)
![6](https://user-images.githubusercontent.com/110963185/191264977-75fe0b0a-dcd9-4489-a312-638b0a5639e7.png)

เจอไอSacc
![1](https://user-images.githubusercontent.com/110963185/191265115-1b113fe6-3426-4633-be64-5bad443ea110.png)
![2](https://user-images.githubusercontent.com/110963185/191265124-66d960af-7916-4d0e-aefd-66056ff92900.png)
![3](https://user-images.githubusercontent.com/110963185/191265129-22e367ac-ed93-4d24-ba89-c4636e11ac55.png)

เจอFinal boss
![1](https://user-images.githubusercontent.com/110963185/191265234-af0f026e-7476-447a-b0fc-4f0f586e49c7.png)
![2](https://user-images.githubusercontent.com/110963185/191265246-267e4275-1136-4557-8f60-bfdfe582b44a.png)
![3](https://user-images.githubusercontent.com/110963185/191265252-8094d2f5-e0d1-42b4-987a-4a436a619ba3.png)
![4](https://user-images.githubusercontent.com/110963185/191265257-479a8bb7-eeb1-4fa6-85e0-fab044211002.png)
![5](https://user-images.githubusercontent.com/110963185/191265262-b545fa07-09f4-40a4-a8d9-f7271a800588.png)
![6](https://user-images.githubusercontent.com/110963185/191265266-bcfc37b9-b9a9-4019-a228-b0e5256ed915.png)
![7](https://user-images.githubusercontent.com/110963185/191265275-0fa07adf-480c-4efb-86df-4126671c4a33.png)
![8](https://user-images.githubusercontent.com/110963185/191265281-25c11ad0-3f53-4b41-bf5d-e05579c376bb.png)
![9](https://user-images.githubusercontent.com/110963185/191265293-f07c8090-5289-4f70-a87f-c22b2c19c57b.png)
![10](https://user-images.githubusercontent.com/110963185/191265321-0c6c475b-d2b2-4447-89e9-f8684c04db9b.png)
