### ISSUE TITLE
ออกแบบ Interface หน้าอัพเกรดไอเทม และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#41]

**Comment by Rehunt671** [comment]
โดยมีรายละเอียดดังนี้ 
1.หน้า Background คือหน้าฐานของปุ่มที่จะอัพเกรด
2.หน้าSprite 3 ไอเทม
3.Sprite ลูกศรไว้เลือกไอเทม

**Comment by Rehunt671** [comment]
โดยหน้า Background ใช้ได้ตลอด 
ลูกศรใช้ได้ตลอด
แต่ที่จะเปลี่ยนคือ Sprite ที่บอกเลเวลในอาวุธแต่ละเวล โดยอาจจะเปลี่ยนรูปอาวุธด้วย???อันนี้แล้วแต่ละแหละ

**Comment by Hewkai** [comment]
ตัวอย่าง
![ตัวอย่าง](https://user-images.githubusercontent.com/110963185/190896944-3e6952d7-6934-4a3d-9db6-844efc727dbe.png)

**Comment by Hewkai** [comment]
หนังสือ
![skill 1](https://user-images.githubusercontent.com/110963185/190909332-f1dfd1c8-8df2-4550-9015-fcb020087f03.png)
![skill 2](https://user-images.githubusercontent.com/110963185/190909499-35d0d9e6-aa87-43a0-8226-c802bddf0ebe.png)
![skill 3](https://user-images.githubusercontent.com/110963185/190909916-16aa510b-94c0-4202-8d3e-5af07a20642b.png)

**Comment by Hewkai** [comment]
ปากกา
![skill 1](https://user-images.githubusercontent.com/110963185/190904161-c061ba38-6c42-48cc-be6b-4329a9a36d45.png)
![skill 2](https://user-images.githubusercontent.com/110963185/190904164-928366ce-647b-4314-ac57-72f4a793507f.png)
![skill 3](https://user-images.githubusercontent.com/110963185/190904167-b3daee18-75e9-41d5-a670-a8ccb5d7d70e.png)

**Comment by Hewkai** [comment]
ค่ายาใจ
![skill 1](https://user-images.githubusercontent.com/110963185/190911462-304d7c35-9da4-4962-9f79-d5366b462acd.png)
![skill 2](https://user-images.githubusercontent.com/110963185/190911467-fac5217a-a490-4e11-bf36-33cec5962c5d.png)
![skill 3](https://user-images.githubusercontent.com/110963185/190911468-aa45a753-fe60-4d04-b6a8-2a7d4871729f.png)

**Comment by Hewkai** [comment]
พื้นหลัง
![NewCanvas3](https://user-images.githubusercontent.com/110963185/191022526-ab78f3cc-3529-478c-965e-7327f3420d8c.png)
