### ISSUE TITLE
ออกแบบ Interface หน้าGame Over(เลือดหมด) และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#42]

**Comment by Hewkai** [comment]
ตัวอย่าง
![full](https://user-images.githubusercontent.com/110963185/191022130-0a94b92f-3f4e-4c65-b850-93309625a2d6.png)

พื้นหลัง
![background](https://user-images.githubusercontent.com/110963185/191022186-ac900a48-7f69-452b-b037-7bca825dc3e9.png)

เล่นใหม่
![again](https://user-images.githubusercontent.com/110963185/191022249-497f4f13-6b76-4739-bfbe-b1da79fba5ce.png)

กลับไปหน้าแรก
![menu](https://user-images.githubusercontent.com/110963185/191022310-14c8361d-cdde-4dd8-abd5-6f77cde39581.png)
