### ISSUE TITLE
ออกแบบ Interface หน้าYou win! และ Import ลง Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#43]

**Comment by Rehunt671** [comment]
ขอแบบมี BG งามๆหน่อย + เสียงเพลง Hollow Knight จนจบจะเยี่ยมมาก
เพลง White palace Hollow Knight Search ได้เลย

**Comment by Hewkai** [comment]
![1](https://user-images.githubusercontent.com/110963185/191265379-32b68587-681f-4656-b19a-a2615fc38147.png)
![2](https://user-images.githubusercontent.com/110963185/191265394-e57c770c-e743-4d97-a82e-fc0c7741ee31.png)
![3](https://user-images.githubusercontent.com/110963185/191266139-134fe46b-4afb-4071-91f1-ccde14d02c65.png)
![4](https://user-images.githubusercontent.com/110963185/191265413-3f631aab-9a71-4f78-8fa4-1bf62d5bd477.png)
