### ISSUE TITLE
Moveset ตัวละครหลัก

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#45]
โดยรวมถึงการอัพเกรดตัว(ตีวงกว้างขึ้น) และกดท่าไม้ตายด้วย(E)

**Comment by Hewkai** [comment]
![Normal Left](https://user-images.githubusercontent.com/110963185/189120927-55519dce-5038-4420-baf8-4a32e029d8ef.png)
![Normal right](https://user-images.githubusercontent.com/110963185/189120935-88d35e9c-92d9-40f0-a1cc-f6f98e634be6.png)
![walk left](https://user-images.githubusercontent.com/110963185/189120941-74678263-064a-4e71-b790-2aee349b8eef.png)
![walk right](https://user-images.githubusercontent.com/110963185/189120948-1c7770a5-737c-4ed2-ae54-963150e3eff1.png)

**Comment by Hewkai** [comment]
ตัวอย่างการตี
![ezgif-2-529f16ecc5](https://user-images.githubusercontent.com/110963185/189150989-dc134851-0d85-487a-85ae-f4a484726a94.gif)

**Comment by Hewkai** [comment]
level 0
![1](https://user-images.githubusercontent.com/110963185/189153571-f9b1a51e-741a-4548-8898-c30795a23406.png)
![2](https://user-images.githubusercontent.com/110963185/189153575-73566821-fcbb-4e1e-987b-0f5c7d186d04.png)
![3](https://user-images.githubusercontent.com/110963185/189153582-f900d571-ab7f-4cab-858d-e6aa2b575a4f.png)
![4](https://user-images.githubusercontent.com/110963185/189153583-dbf48412-c9d4-4150-952f-f39317584c1e.png)
![5](https://user-images.githubusercontent.com/110963185/189153588-b71a0774-ada2-4ea5-96da-21d2b24f4706.png)
![6](https://user-images.githubusercontent.com/110963185/189153590-5c3d8869-fa0a-4ece-8155-968a5fe963b2.png)

**Comment by Hewkai** [comment]
![ezgif-5-a6626072c4](https://user-images.githubusercontent.com/110963185/189161327-150e1021-39cf-48f2-af81-9bf1ea7bc518.gif)

**Comment by Hewkai** [comment]
level 1
![11](https://user-images.githubusercontent.com/110963185/189161512-f7cefb08-c337-4c01-b306-797a32b32a52.png)
![12](https://user-images.githubusercontent.com/110963185/189161525-e21402b3-1c47-4ac4-bb4b-fa69fd32ec5d.png)
![13](https://user-images.githubusercontent.com/110963185/189161533-84105576-7a18-441b-a5a5-9319593059a8.png)
![14](https://user-images.githubusercontent.com/110963185/189161537-5a355136-a8a7-4886-b6af-d3c9688da482.png)
![15](https://user-images.githubusercontent.com/110963185/189161539-322895aa-a246-4b4a-b3fb-fa020952e831.png)
![16](https://user-images.githubusercontent.com/110963185/189161545-b89cbea9-d661-4af3-af4e-220e9d645f04.png)

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189166413-8742b894-775e-45fa-8f65-8ea93ad6bff2.png)

**Comment by Rehunt671** [comment]
โค้ดของการทำงานวันแรก

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189166541-6834ebb9-2364-4f19-ba42-8cb92f9c16a9.png)

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189511280-34016622-a4c7-4b8d-8549-b9038b6d1b0b.png)

**Comment by Rehunt671** [comment]
โค้ดตัวละครวันที่ 11

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189529287-f0eb3faa-b93f-472c-a054-54c3c2f83d82.png)
สร้าง Abstraction แยกกรณีโดนมอนตีเพื่อง่ายต่อการแก้โค้ด

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189529406-363e551f-bde4-4b8b-89c8-c83c6cb83b7b.png)

**Comment by Hewkai** [comment]
level 2
![ezgif-3-acc203aa6d](https://user-images.githubusercontent.com/110963185/189533211-78a0472e-1525-4b35-ae63-5d555e984942.gif)
![21](https://user-images.githubusercontent.com/110963185/189533227-1772ef25-c004-46c4-8b2e-2c526298ebe6.png)
![22](https://user-images.githubusercontent.com/110963185/189533228-e82c1220-0fb4-4d5a-a04c-eb840b856301.png)
![23](https://user-images.githubusercontent.com/110963185/189533231-3387b0b7-f8ec-4997-82af-28fa8adcd6bc.png)
![24](https://user-images.githubusercontent.com/110963185/189533233-9fb67526-aa58-476c-bb22-263905a6d345.png)
![25](https://user-images.githubusercontent.com/110963185/189533234-16acbae6-863a-4666-9762-5780df219c72.png)
![26](https://user-images.githubusercontent.com/110963185/189533235-6cce2476-b33b-492f-9fba-e9c53df75ca0.png)
![27](https://user-images.githubusercontent.com/110963185/189533236-0b6bf45f-bf98-4e7b-a585-2fc325df1c1a.png)

**Comment by Hewkai** [comment]
level 3
![ezgif-4-be94fbaae1](https://user-images.githubusercontent.com/110963185/189534470-5b2b2f21-152e-408b-ada0-25181c55e866.gif)
![31](https://user-images.githubusercontent.com/110963185/189534474-79a26e4d-a5a1-488c-a910-2fc20af9079b.png)
![32](https://user-images.githubusercontent.com/110963185/189534475-59468478-7d2a-4e52-8dae-b99b43eeca0a.png)
![33](https://user-images.githubusercontent.com/110963185/189534476-b74bb4f3-aa2f-4459-a68f-48004369f1c7.png)
![34](https://user-images.githubusercontent.com/110963185/189534479-c2a6358b-bf8e-493b-9817-e8d31dc261c1.png)
![35](https://user-images.githubusercontent.com/110963185/189534481-4efd7733-de37-432c-ba59-98c2a3648e1b.png)
![36](https://user-images.githubusercontent.com/110963185/189534483-d286fc69-5c90-4320-9b13-4c8d27d09845.png)

**Comment by Hewkai** [comment]
ตอนใช้ท่าไม่ตาย
![ezgif-5-d2c240b14c](https://user-images.githubusercontent.com/110963185/189695816-805c676f-4702-486f-bad3-ef241d359fde.gif)
หันซ้าย
![1](https://user-images.githubusercontent.com/110963185/189695850-4a271e7f-c283-4e95-9e27-fc406c9f71be.png)
![2](https://user-images.githubusercontent.com/110963185/189695855-5b29308f-7605-4717-b198-01c79d4450d2.png)
![3](https://user-images.githubusercontent.com/110963185/189695857-48665d0b-90b9-4452-aadf-8b0b8fe69ca6.png)
![4](https://user-images.githubusercontent.com/110963185/189695859-f9ce20d3-5157-42c2-a2f0-7d166a4b5d45.png)
![5](https://user-images.githubusercontent.com/110963185/189695864-c221102c-db1a-4b37-8a10-86743aea81fe.png)
![6](https://user-images.githubusercontent.com/110963185/189695865-1fc4d089-b329-4435-9e35-6c042cb19e25.png)
หันขวา
![1 r](https://user-images.githubusercontent.com/110963185/189696467-097a0edf-99eb-409b-a049-9679fcc4aa5e.png)
![2 r](https://user-images.githubusercontent.com/110963185/189696473-0cf27dbd-7241-428e-b6ca-05a5c583a209.png)
![3 r](https://user-images.githubusercontent.com/110963185/189696479-79a2e544-3a30-488d-b635-0f22d99dca4c.png)
![4 r](https://user-images.githubusercontent.com/110963185/189696483-9efbe190-2e71-4c9b-acf9-db071ed2792b.png)
![5 r](https://user-images.githubusercontent.com/110963185/189696484-e92db714-c36b-4a45-b3c5-6730aa0a7b51.png)
![6 r](https://user-images.githubusercontent.com/110963185/189696487-53294d37-44cb-4da1-a248-097ffcbdf63a.png)
