### ISSUE TITLE
Moveset Monster ไม้ที

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#46]
โดยมีรายละเอียดดังนี้
-มีความเร็วการเคลื่อนที่ของมอน
-มีปริมาณเลือด
-Knock back

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189166731-7491ba69-fed1-48e5-8564-9a3e7ef34253.png)

**Comment by Rehunt671** [comment]
โค้ดของตัวละครไม้ที โดยที่ยังไม่ได้ลงรายละเอียด และ รูปตัวละครในวันแรก

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189166994-12dae142-3abd-435b-8f7d-81a065f27f60.png)

โดยกำหนดให้เป็นตัวนี้ไปก่อน

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189337591-5981b632-f08c-4943-bdb1-4051c1d90a12.png)
แก้ไขโด้ดเงื่อนไขการเกิดของไม้ที
