### ISSUE TITLE
Moveset Monster ไม้45

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#47]
โดยมีรายละเอียดดังนี้
-มีความเร็วการเคลื่อนที่ของมอน
-มีปริมาณเลือด
-Knock back

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189167098-8c11a2c6-07be-453b-9f83-907571596315.png)
ตัวละครและโค้ดของมอนไม้ 45

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189167245-69cc693f-3818-44cf-ad52-5b5c20ee6837.png)

โดยยังไม่ได้ลงรูปแต่ใช้ Sprite ตัวนี้ไปก่อน

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189338137-9991d29f-8667-4c08-95d9-2cd64154fbc1.png)
แก้ไขโค้ดเงื่อนไขการเกิดของไม้45
