### ISSUE TITLE
Moveset Monster ไม้ 30 

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#48]
โดยมีรายละเอียดดังนี้
-มีความเร็วการเคลื่อนที่ของมอน
-มีปริมาณเลือด
-Knock back

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189167409-00a6699f-866e-4461-822e-65bce41f961a.png)

โค้ดจะคล้ายๆกับตัวละครตัวอื่นแต่เราจะเปลี่ยน รายละเอียดยิบย่อย เช่นเลือด หรือความเร็วการเคลื่อนที่ในภายหลัง

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189167551-a58de9d2-cc3b-41e9-a52b-5a2bd7643ef9.png)

ใช้ตัวละครนี้ไปก่อน

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189338637-6af3ea84-93f2-430e-8468-2131ccc36848.png)
แก้ไขโค้ดเงื่อนไขการเกิดของไม้ 30
