### ISSUE TITLE
Moveset Monster หน้าX(ตีใกล้)ของแคลคูลัส

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#49]
โดยมีรายละเอียดดังนี้
-มีความเร็วการเคลื่อนที่ของมอน
-มีปริมาณเลือด
-Knock back

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/190082920-16c5ac7a-1c4e-4d09-a3d5-a15361b84799.png)
![image](https://user-images.githubusercontent.com/110970005/190082961-23671026-d234-452b-ba80-3b84173f232a.png)
![image](https://user-images.githubusercontent.com/110970005/190082997-dc8b5c36-fea2-4ed4-9b13-e89c89aa537e.png)
