### ISSUE TITLE
Moveset Monster พลธนูวิชาแคล

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#50]
โดยมีรายละเอียดดังนี้
-มีความเร็วการเคลื่อนที่ของมอน
-มีปริมาณเลือด
-Knock back

**Comment by Nina-pw** [comment]
![Code-4](https://user-images.githubusercontent.com/110963696/189207527-de4aa577-454d-4a9f-b2e9-8b16cc0c4d21.png)
![Code-5](https://user-images.githubusercontent.com/110963696/189207537-98a315d3-cbfa-427f-8181-27124acdd6fa.png)

**Comment by Nina-pw** [comment]
![Code-4](https://user-images.githubusercontent.com/110963696/189208379-aa770c65-a112-4cc6-9755-f9428b0627fc.png)
![Code-5](https://user-images.githubusercontent.com/110963696/189208388-e30f4d4e-c5b4-46d5-8036-152b49c7bf71.png)

**Comment by Nina-pw** [comment]
ยังไม่สมบูรณ์แบบนะ เดี๋ยวพน.มาแก้ต่อ

**Comment by Nina-pw** [comment]
![2](https://user-images.githubusercontent.com/110963696/189390807-6b00b18f-1e75-4d56-8f49-e57c6decabb5.png)
![3](https://user-images.githubusercontent.com/110963696/189390816-3faa2676-c7cb-402b-be0f-9b87867ba0b3.png)
![4](https://user-images.githubusercontent.com/110963696/189390819-93370453-a9b4-4bcf-a025-a9e62db130ea.png)
แก้ไข Code

**Comment by Nina-pw** [comment]
การโจมตีของพลธนูจะเป็นการโจมตีก็ต่อเมื่อระยะห่างของตัวละครและ Monster น้อยกว่า 150 จากนั้นพลธนูก็จะทำการยิงธนูโจมตีและเมื่อมีระยะห่างมากกว่า 150 Monster ก็จะไล่ตามและยิงธนูโดยทำซ้ำแบบนี้ไปเรื่อยๆ นั่นเอง

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/189391911-dbb60942-66fa-4b84-ada4-1c3a16c69aec.mp4

**Comment by Nina-pw** [comment]
หมายเหตุ: ตัวละครที่ลองใช้ในการเขียน Code ไม่ใช่ตัวละครจริงๆ แต่โดยรวมการเคลื่อนที่ของ Monster พลธนูวิชาแคลจะเป็นแบบนี้

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189528160-1f9b97dd-033a-4ba7-86f8-4cb01b595e07.png)
moveset ตัวธนูหลังรวมไฟล์

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189528198-ac747315-f4ac-436a-aff8-0f2c328deb59.png)
moveset ลูกธนูหลังรวมไฟล์

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189528840-3c29d262-7695-4ea9-98dd-28d03b47d632.png)

แก้โค้ดลูกธนู

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189528861-2b5661c3-ca24-4035-9357-ee5285bb0733.png)
แก้โค้ดการเดินตัวธนู
