### ISSUE TITLE
Moveset Monster วงเวียน

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#52]

**Comment by Rehunt671** [comment]
ทำให้โจมตีเป็นวงรอบตัวได้ (สกิล)

**Comment by Nina-pw** [comment]
![1](https://user-images.githubusercontent.com/110963696/189369861-0b4264f5-57da-49ff-840b-e4453300ea25.png)

**Comment by Nina-pw** [comment]
การโจมตีของ Monster วงเวียน จะโจมตีก็ต่อเมื่อระยะห่างจากตัวละครน้อยกว่า 80 และเมื่อมากกว่า 80 ก็จะไล่ตามและโจมตีต่อไปเรื่อยๆ โดยรวมก็จะทำในส่วนของ Moveset Monster วงเวียน เป็นหลัก

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/189372096-296d2fdc-0e38-4210-9bc6-1fe443f428a6.mp4

**Comment by Nina-pw** [comment]
หมายเหตุ: ตัวละครที่ลองใช้ในการเขียน Code ไม่ใช่ตัวละครจริงๆ แต่โดยรวมการเคลื่อนที่ของ Monster วงเวียน เป็นแบบนี้
