### ISSUE TITLE
Moveset Final Boss Scratch

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#55]
กระโดดทับโดนทีตาย

**Comment by Hewkai** [comment]
![down1](https://user-images.githubusercontent.com/110963185/189145265-52350081-e4f6-43fe-8d5d-b1b02be56061.png)
![down2](https://user-images.githubusercontent.com/110963185/189145275-481bf10f-4b07-45fa-8fbf-d21bfc420828.png)
![normal](https://user-images.githubusercontent.com/110963185/189145283-c358de9e-6a4a-4d76-89ea-431b49953a12.png)
![up1](https://user-images.githubusercontent.com/110963185/189145285-b80fefe0-e871-422c-b1b4-f51c682eee0b.png)
![up2](https://user-images.githubusercontent.com/110963185/189145292-b3de9e38-7ea0-4d71-ab7f-608442e4cbcc.png)

**Comment by Hewkai** [comment]
ตอนกระโดด
![ezgif-1-9dcfcf1532](https://user-images.githubusercontent.com/110963185/189145537-581dfeb3-ba04-433a-b2ad-df0e84dfafde.gif)

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189167666-d4446f67-3f11-4c2f-bcc1-684cd5821398.png)
โค้ดกระโดดของบอส

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189168076-6d08b131-25f1-488b-9604-41a6be837998.png)

**Comment by Maimeetang** [comment]
แก้ไขโค้ด moveset final boss
![image](https://user-images.githubusercontent.com/110970005/189347503-67f74e56-18c5-4177-ab1f-8caa81c745f5.png)
