### ISSUE TITLE
ทำให้ item Energy drink ฮีลได้จิง

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#58]

**Comment by Rehunt671** [comment]
โดยใช้ในการยืนเพื่อสู้มอน ไอเทมนี้จะเพิมเลือด 50 แต้ม

**Comment by Nina-pw** [comment]
![1](https://user-images.githubusercontent.com/110963696/189576392-b491f972-5fcb-4374-beb7-9de74112a857.png)

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/189577465-0eac663e-caf2-45a2-9c55-ae0262346435.MOV

**Comment by Nina-pw** [comment]
โดย Item Energy drink จะทำการเพิ่มเลือดในแต่ละครั้งที่เก็บ และจะมีให้เก็บในทุกๆ 10 วินาทีหลังจากเก็บไปนั่นเอง
