### ISSUE TITLE
สร้างเงื่อนไขจบ Wave

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#60]
คือทุก 30 วิ เปลี่ยน Wave แบ่งเป็น  5 wave แรกเจอมอนดรออิ้ง -> บอสดรออิ้ง(มอนหยุดเกิด)-> 5 wave ครั้งที่สองเจอมอนCal -> บอสแคล(มอนหยุดเกิด) -> มันแคล+ฟิสิกส์ -> บอสฟิสิกส์(มอนหยุดเกิด)-> บอส Final

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189169450-48a50423-a704-4e11-a699-00e74948ed70.png)

เงื่อนไขการจบ Wave จะขึ้นกับตัวแปร เวลาและนี่คือคือโค้ดของวันแรก

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189327088-e72f360d-ad7b-4e29-a7ff-0316bfa6c270.png)
สร้างโค้ด wave แยก

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/189336355-7d56b70f-ad6b-4232-83c7-ba47f0e4173f.png)
แก้ไขโค้ด
