### ISSUE TITLE
Opening ฉากเปิดเกม

### ISSUE THREAD

**Issue by Nina-pw** [Asura671/Scratch-game-for-group-8#61]
เพื่อให้เกมมีความน่าสนใจ ควรมีการเปิดเกมโดยดึงดูดความสนใจจากผู้เล่น

**Comment by Nina-pw** [comment]
![Code-1](https://user-images.githubusercontent.com/110963696/189181839-202bc222-18c3-4ab5-b411-e41b7ee3efa8.png)
![Code-2](https://user-images.githubusercontent.com/110963696/189181847-5d22c17f-e371-46cb-9060-7f65b1082794.png)
![Code-3](https://user-images.githubusercontent.com/110963696/189181903-45f6ddd5-7525-414e-a7c3-498cdfcf4b73.png)

**Comment by Nina-pw** [comment]
โดยคร่าวๆ การเขียนโค้ดจะเป็นประมาณนี้

**Comment by Nina-pw** [comment]
หลังจากการเปิดฉากก็จะเป็นหน้าการเริ่มเกมและคู่มือตามลำดับ

**Comment by Nina-pw** [comment]
![Code-1](https://user-images.githubusercontent.com/110963696/189208171-f6fccc6c-b312-4b1b-9c7c-b47f8311a570.png)
![Code-2](https://user-images.githubusercontent.com/110963696/189208178-5b976bf0-10ef-4335-9e19-a10dcfab296a.png)
![Code-3](https://user-images.githubusercontent.com/110963696/189208185-c9fe0019-5282-4483-b668-3bd6ce166e15.png)

**Comment by Nina-pw** [comment]
ก็คือโดยคร่าวๆได้ลองใส่ sound และ effect ต่างๆไปแล้วโดยรวมก็ถือว่าได้อยู่นะ

**Comment by Rehunt671** [comment]
เยียมๆ
