### ISSUE TITLE
ขอ Health Bar & Stamina bar ด้วยสำหรับตัวละครหลัก -0-

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#73]
![image](https://user-images.githubusercontent.com/105868841/189510650-ff3afe99-70f4-40a4-bbaa-7284411ad366.png)
รูปแบบจะคล้ายๆแบบนี้ขอเป็นสัก 10 ช่วงก็ได้มั้ง 1-10 11-20 21-30 31-40 41-50 51-60 61-70 71-80 81-90 91-100

**Comment by Asura671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189510635-326ae626-7b90-4a6a-b9c2-5b7947c3f3c2.png)

**Comment by Rehunt671** [comment]
เพิ่มเติม เลือดไอคอนสีเขียว แต้ Stamina สีเหลือง

**Comment by Rehunt671** [comment]
เพิ่มเติมอีกสักหน่อย
คือจะให้หลอดเลือดผสมเหลืองตอนเลือดกลางๆก็ได้
และ Stamina เหลืองล้วนก็ดีเช่นกัน
แล้วแต่เลย

**Comment by Hewkai** [comment]
อันนี้คือเพื่อนทำใช่ปะ

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/191268325-df7a4d2e-9ec8-4680-88bf-94b4232f9919.png)
