### ISSUE TITLE
บัคระบบ อมตะค่ายาใจและหลังโดนมอนตี ณ วันที่ 19

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#77]
ทำงานผิดพลาดโดยตอนอมตะแล้วโดนโจมตีแล้วระบบเอาดาเมจมาลบทีหลังทั้งๆไม่ได้โดนโจมตีแล้ว

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/189531444-e389f981-0528-49c0-ac75-8d81076d4ead.png)

แก้ไขโดย ใช้ If เช็คเงื่อนไข 2 ชั้น

**Comment by Rehunt671** [comment]
ตอนนี่คือมันไปเกิดกับมอนทุกตัวและ ค่ายาใจอีกรอบ

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/190998376-01b66913-aeb0-4556-bb74-39a6860a4f2e.png)
ลองเทสดูแล้วไม่บัคละ
