### ISSUE TITLE
บัค บอสแคลไร้พ่าย สมแล้วจริงๆที่เป็นวิชาแคลขนาดในเกมยังปวดหัวกับมัน

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#78]
![image](https://user-images.githubusercontent.com/105868841/189540718-ad1e9f1f-425e-4f5b-961c-2a640e311826.png)

**Comment by Rehunt671** [comment]
คือบอสมันเลือดน้อยกว่า 0 แล้วไม่ตาย

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/190082483-ac0a18ad-6a2a-4682-a028-5f1e732a8f1f.png)
![image](https://user-images.githubusercontent.com/110970005/190082534-872a4cbd-c798-417f-a336-154cc5c5719d.png)
![image](https://user-images.githubusercontent.com/110970005/190082573-037eaee8-3c08-416a-8123-8b5868529d3a.png)
![image](https://user-images.githubusercontent.com/110970005/190082608-def4f253-5cf9-44eb-a463-15f4d3163124.png)
แก้บัคบอสแคล
