### ISSUE TITLE
ระบบเลเวล

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#79]
อยากให้มีการอัพเลเวลจากการฆ่ามอน และ ทำให้อัพเกรดอาวุธได้

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/190898280-2eb39ba1-fb15-490e-8b0d-100481fed82f.png)
ระบบเลเวล

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/190898323-a95bb5fd-3a6d-4b5e-ac1b-bdb43f9f15af.png)
เพิ่มเงื่อนไขในมอนแต่ละตัว
