### ISSUE TITLE
ออกแบบพื้นหลังและสิ่งกีดขวาง ทุกด่าน

### ISSUE THREAD

**Issue by Hewkai** [Asura671/Scratch-game-for-group-8#83]
แผนที่รวม 1
![full1](https://user-images.githubusercontent.com/110963185/190411945-2f4db628-d1fe-48d3-b2aa-bbbe613a180e.png)
พื้นหลัง
![1](https://user-images.githubusercontent.com/110963185/190412026-4686132e-42c8-4cd2-bb81-a42860a57fe8.png)
สิ่งกีดขวาง
![สิ่งกีดขวาง1](https://user-images.githubusercontent.com/110963185/190412335-c50cc521-2f1a-4265-a41e-c6780130f8d9.png)

**Comment by Hewkai** [comment]
แผนที่รวม2
![full2](https://user-images.githubusercontent.com/110963185/190843419-74d14295-7691-419f-a841-840596e5775c.png)
พื้นหลัง
![2](https://user-images.githubusercontent.com/110963185/190843427-c5cb37aa-fd91-4ed9-a81d-21da23087e73.png)
สิ่งกีดขวาง
![สิ่งกีดขวาง2](https://user-images.githubusercontent.com/110963185/190843435-fd21cfb0-3724-4794-acba-6ae56ebb2039.png)
แสง
![เอฟเฟก2](https://user-images.githubusercontent.com/110963185/190843441-89ae4d51-f00e-4731-b1b2-1f6b09413c4b.png)

**Comment by Hewkai** [comment]
> แผนที่รวม2 ![full2](https://user-images.githubusercontent.com/110963185/190843419-74d14295-7691-419f-a841-840596e5775c.png) พื้นหลัง ![2](https://user-images.githubusercontent.com/110963185/190843427-c5cb37aa-fd91-4ed9-a81d-21da23087e73.png) สิ่งกีดขวาง ![สิ่งกีดขวาง2](https://user-images.githubusercontent.com/110963185/190843435-fd21cfb0-3724-4794-acba-6ae56ebb2039.png) แสง ![เอฟเฟก2](https://user-images.githubusercontent.com/110963185/190843441-89ae4d51-f00e-4731-b1b2-1f6b09413c4b.png)

*อยากให้มอนออกมาจากใต้โต๊ะ

**Comment by Hewkai** [comment]
แผนที่รวม3
![full3](https://user-images.githubusercontent.com/110963185/190850601-ed4ffb27-cfe5-4e99-9473-a72751d4e534.png)
พื้นหลัง
![3](https://user-images.githubusercontent.com/110963185/190850805-7b1839f7-0d0b-45a5-99e6-fb7461d31c8a.png)

สิ่งกีดขวาง

![สิ่งกีดขวาง3](https://user-images.githubusercontent.com/110963185/190850853-e72ab042-7a9f-4f18-80d1-2b1f4ede5ddc.png)

**Comment by Rehunt671** [comment]
![image](https://user-images.githubusercontent.com/105868841/190886841-807aa899-d0e0-49ae-8cb3-eb997ed74473.png)

**Comment by Rehunt671** [comment]
Hit box ด้านบนมันเยอะอะ กับขนาดไม่พอดี
