### ISSUE TITLE
ทำให้เดินชนสิ่งกีดขวางแล้วเดินติด

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#90]

**Comment by Nina-pw** [comment]
https://user-images.githubusercon

https://user-images.githubusercontent.com/110963696/190956115-7b3e6ed2-5730-4b28-a798-773ed52e50fe.MP4


https://user-images.githubusercontent.com/110963696/190956101-7f328dbb-c1ca-400b-98f9-4da0555e5d78.MP4

tent.com/110963696/190956093-dfe269e9-2b88-4800-8f7d-6d75b4f4d9fb.MP4

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/190956216-2c1d6bce-790c-41ae-afa9-7396ada30a1b.MP4

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/190956263-cfed5924-e7c6-42b4-8ab1-25580975b5c5.MP4

**Comment by Nina-pw** [comment]
https://user-images.githubusercontent.com/110963696/190956291-33296ab5-ad93-4467-884b-622e6e08fc8e.MP4
