### ISSUE TITLE
Show icon ณ เลเวลต่างๆ 1-2เหมือนกัน 3 จะเปลี่ยนรูป(หลังอัพเวล)

### ISSUE THREAD

**Issue by Rehunt671** [Asura671/Scratch-game-for-group-8#92]

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/191235383-e6959c04-7462-47f5-b8bd-eb6cb48e645b.png)
ปากกา
![image](https://user-images.githubusercontent.com/110970005/191235467-d092b3cd-9741-4496-9265-5700e4c9aff5.png)
ยาใจ
![image](https://user-images.githubusercontent.com/110970005/191235514-9f2c092c-4bcc-4aa3-a9b7-8bc48499077e.png)
หนังสือ
