### ISSUE TITLE
ฉากเริ่มเกม

### ISSUE THREAD

**Issue by Hewkai** [Asura671/Scratch-game-for-group-8#97]

**Comment by Hewkai** [comment]
![1](https://user-images.githubusercontent.com/110963185/191254454-fb47b471-ba75-442c-9773-5745c843126f.png)
![2](https://user-images.githubusercontent.com/110963185/191254465-1ba0fea6-2512-4df9-a541-1239a6f36f54.png)
![3](https://user-images.githubusercontent.com/110963185/191254469-d5c47ea6-74b4-46cf-8ab2-b43dc39fad70.png)
![4](https://user-images.githubusercontent.com/110963185/191254473-9fe3a806-989b-4338-a14b-f8adc5cde177.png)
![5](https://user-images.githubusercontent.com/110963185/191254475-78e27aef-5fed-4f66-a929-51f126b8c71a.png)

**Comment by Rehunt671** [comment]
![191254469-d5c47ea6-74b4-46cf-8ab2-b43dc39fad70 (1)](https://user-images.githubusercontent.com/105868841/191424008-f30c554c-4188-4174-bcae-8c63672047a3.png)
